//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webshop2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Payment { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
